#!/bin/bash

# parses file generated by gen-blocklist.sh and copies assets files that are followed by a 1 in the blocklist

# usage
# cp-textures.sh /minecraft/assets/folder ./blocklist.txt ./blockimgs

path_to_block_files=$1 # exclude '/' at the end
blocklist=$2
output_dir=$3

mkdir -p $output_dir
echo $path_to_block_files
while read line; do
    IFS=" " read file include <<< $line

    img_path="${path_to_block_files}/${file}"

    include=$(echo $include | tr -dc '0-1')    

    case $include in
    "1")
        echo "adding... ${file}"
        cp $img_path $output_dir
    ;;
    "0")
        echo "omitting: ${file}"
    ;;
    esac
done < $blocklist
